# Python version
FROM python:3.9

# Set a working directory
WORKDIR /usr/src/loan-predictor

# Copy all the files to the container
COPY . .

# Install Dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Set port to expose app
EXPOSE 5000

# Run the app
CMD ["python", "./app_fast_local.py"]
